name: reputify
version: '1.0.0'
main: net.hynse.reputify.Reputify
api-version: '1.20'
folia-supported: true
commands:
  rep:
    description: Manage player reputation.
    usage: /rep [player]
    aliases: [ reputation ]
    permission: reputify.view
  repadmin:
    description: Manage player reputation admin commands.
    usage: /repadmin <set|add|remove> <player> <points>
    aliases: [ reputationadmin ]
    permission: reputify.manage

permissions:
  reputify.manage:
    description: Allows the player to manage reputation using the /repadmin command.
    children:
      reputify.manage.add: true
      reputify.manage.remove: true
      reputify.manage.set: true
    default: op
  reputify.view:
    description: Allows the player to view their own reputation points using the /rep command.
    children:
      reputify.view.other: true
    default: true
  reputify.view.other:
    description: Allows the player to view other players' reputation points using the /rep command.
    default: false

soft-depend:
  - PlaceholderAPI
